routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['web']], function () {


	Route::get('clear', function (){
    	\Artisan::call('config:cache');
        \Artisan::call('cache:clear');
        \Artisan::call('route:clear');
        \Artisan::call('view:clear');
        \Artisan::call('storage:link');
        echo "ok";
	});

	// Route::get('/link', function () {        
 //   		$target = '/kunden/351322_8001/web/2709369/A2709369/autokosmetik.li/storage/app/public';
 //   		//echo public_path();
 //   		$shortcut = '/kunden/351322_8001/web/2709369/A2709369/autokosmetik.li/public/storage';
 //   		symlink($target, $shortcut);
	// });

	
	Route::get('/register',function () {return redirect('admin/login'); });
	/* Authentication Routes... */
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	  
	/* Registration Routes... */
	//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
	//Route::post('register', 'Auth\RegisterController@register');
	  
	/* Password Reset Routes... */
	// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
	// Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
	  
	/* Email Verification Routes... */
	// Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
	// Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
	// Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

	Route::get('/', function () {
	     return redirect('admin/vehicletypes');
	});
	Route::group(['middleware' => 'auth'], function () {
		/*Vehicle Type Route*/
		Route::resource('/vehicletypes', 'VehicleTypeController');  
		Route::resource('/servicecategories', 'ServiceCategoryController');
		Route::resource('/servicesubcategories', 'ServiceSubCategoryController');
        Route::resource('/vehiclecategories', 'VehicleCategoryController');  
		Route::resource('/vehicleconditions', 'VehicleConditionsController');  
		Route::resource('/vehiclebrands', 'VehicleBrandsController');  
		Route::resource('/drivevehicles', 'DriveVehicleController');
		Route::resource('/vehicleservices', 'VehicleServicesController');  
		Route::resource('/servicemangement', 'ServiceManagementController');
        Route::resource('/portfolio', 'PortfolioController');
        Route::resource('/news', 'NewsController');
        Route::resource('/addonservice', 'AddonserviceController');
        Route::resource('/feedback', 'FeedbackController');
	});    
});

routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/

Route::get('/', 'WebsiteController@comingsoon')->name('comingsoon');


Route::get('/foo', function () {
    Artisan::call('storage:link');
});




Route::group(['prefix' => 'second_skin'], function() {

	Route::get('/',  'WebsiteController@second_skin')->name('index');

});

Route::group(['prefix' => ''], function() {

	Route::get('/', 'WebsiteController@index')->name('index');

	Route::get('/home', 'WebsiteController@index')->name('index');

	Route::get('/autoaufbereitung', 'WebsiteController@aboutUs')->name('about.us');

	Route::get('/news', 'WebsiteController@news')->name('news');

	Route::get('/news/{id}', 'WebsiteController@newsDetails')->name('newsDetails');

	Route::get('/dienstleistungen', 'WebsiteController@services')->name('services');

	Route::get('/car-cosmetics', 'WebsiteController@carCosmetics')->name('car.cosmetics');

	Route::get('/foil-technology', 'WebsiteController@foilTechnology')->name('foil.technology');

	Route::get('/rim-tire', 'WebsiteController@rimTire')->name('rim.tire');

	Route::get('/voucher', 'WebsiteController@voucher')->name('voucher');

	Route::get('/kontakt', 'WebsiteController@contact')->name('contact');

	Route::get('/projekte', 'WebsiteController@portfolio')->name('portfolio');

	Route::get('/keramikbeschichtung-servfaces', 'WebsiteController@ceramic_coating')->name('ceramic_coating');

	Route::get('/Termin-buchen', 'WebsiteController@bookappointment')->name('bookappointment');

	Route::get('/teflonversiegelung', 'WebsiteController@sealing')->name('sealing');

	Route::get('/swissvax', 'WebsiteController@swissvax')->name('swissvax');

	Route::get('/herkömmlich', 'WebsiteController@conventinal')->name('conventinal');

	Route::get('/spezialfälle', 'WebsiteController@specialcase')->name('specialcase');

	Route::get('/foiltech', 'WebsiteController@foiltech')->name('foiltech');

	Route::get('/lack', 'WebsiteController@paint')->name('paint');

	Route::get('/mono', 'WebsiteController@mono')->name('mono');
	
	Route::get('/autopflege-swissvax', 'WebsiteController@carcare_swissvax')->name('carcare_swissvax');
	Route::get('/auto-innenreinigung', 'WebsiteController@car_interior_cleaning')->name('car_interior_cleaning');
	Route::get('/auto-innenaufbereitung-spezial', 'WebsiteController@car_interior_processing_special')->name('car_interior_processing_special');
	Route::get('/steinschlagschutzfolie', 'WebsiteController@stone_impact_protection_film')->name('stone_impact_protection_film');
	Route::get('/autoscheibentoenung', 'WebsiteController@car_window_tinting')->name('car_window_tinting');
	Route::get('/lederpflege-lederrestauration', 'WebsiteController@leather_care_restoration')->name('leather_care_restoration');
	Route::get('/autofolierung-car-wrapping', 'WebsiteController@car_wrapping')->name('car_wrapping');
	Route::get('/fahrzeugbeschriftung', 'WebsiteController@vehicle_lettering')->name('vehicle_lettering');
	Route::get('/wassertransferdruck', 'WebsiteController@water_transfer_printing')->name('water_transfer_printing');
	Route::get('/verchromungen', 'WebsiteController@chrome_plating')->name('chrome_plating');
	Route::get('/interieur-design', 'WebsiteController@interior_design')->name('interior_design');

	
	

	
	


	Route::get('/email',  function () {

	   $logo = public_path().'/assets/frontend/images/logo.png';

	    return view('frontend.email_template',['name'=>'Wolfinger Fabio','insert_id'=>'9','today' =>'11. April 2021','email'=>'shravangoswami@gmail.com','number'=>'1234567890','logo' => $logo]);

	});

	Route::get('/inquiry',  function () {

	    return view('frontend.inquiry');

	})->name('inquiry');



	Route::post('/step0', 'WebsiteController@ajaxStep0')->name('ajax.step0');

	Route::post('/step1', 'WebsiteController@ajaxStep1')->name('ajax.step1');

	Route::post('/step2', 'WebsiteController@ajaxStep2')->name('ajax.step2');

	Route::post('/step20', 'WebsiteController@ajaxStep20')->name('ajax.step20');

	Route::post('/step3', 'WebsiteController@ajaxStep3')->name('ajax.step3');

	Route::post('/step4', 'WebsiteController@ajaxStep4')->name('ajax.step4');

	Route::post('/step5', 'WebsiteController@ajaxStep5')->name('ajax.step5');

	Route::post('/step6', 'WebsiteController@ajaxStep6')->name('ajax.step6');

	Route::post('/step7', 'WebsiteController@ajaxStep7')->name('ajax.step7');

	Route::post('/step8', 'WebsiteController@ajaxStep8')->name('ajax.step8');





	Route::post('/contactform1', 'WebsiteController@contactform1')->name('ajax.contactform1');

});

resources/views/backend/driver_vehicle/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>  {{ trans('global.create') }} {{ trans('cruds.drivevehicles.title_singular') }}</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('drivevehicles.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                 @include("partials.alert")
                <form action="{{ route('drivevehicles.store') }}" method="POST" enctype="multipart/form-data" id="add_form">
                    @csrf
                   
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.drivevehicles.fields.name') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', isset($drivevehicles->name) ? $drivevehicles->name : '') }}">
                    </div>
                   
                    <div class="form-group">
                        <label for="model">{{ trans('cruds.drivevehicles.fields.modal') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="model" name="model" value="{{ old('model', isset($drivevehicles->model) ? $drivevehicles->model : '') }}">
                    </div>

                    <div class="form-group">
                        <label for="category">{{ trans('cruds.drivevehicles.fields.vehicle_category') }}<span class="required_class">*</span></label>
                        <select class="form-control" name="vehicle_categorie_id" >
                            <option value="">{{ trans('cruds.drivevehicles.fields.select_vehicle_category') }}</option>  
                            @foreach($vehicle_category as $value)
                                <option value="{{$value->id}}" >{{$value->name}}</option>  
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="category">{{ trans('cruds.drivevehicles.fields.vehicle_brand') }}<span class="required_class">*</span></label>
                        <select class="form-control" name="vehicle_brand_id" id="vehicle_brand_id">
                            <option value="">{{ trans('cruds.drivevehicles.fields.select_vehicle_brand') }}</option>  
                            @foreach($vehicle_brands as $value)
                                <option value="{{$value->id}}" data-value-temp="{{$value->vehicle_type_ids}}">{{$value->name}}</option>  
                            @endforeach
                        </select>
                    </div>
                    
                    <div class="form-group car_window_selection" style="display: none">
                        <label for="model">{{ trans('cruds.drivevehicles.fields.number_of_window') }}</label><br>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_3" value="3" checked="">
                            <label class="form-check-label" for="bike_3">3</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_5" value="5">
                            <label class="form-check-label" for="bike_5">5</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_7" value="7">
                            <label class="form-check-label" for="bike_7">7</label>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="price">{{ trans('cruds.drivevehicles.fields.price') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="price" name="price" value="{{ old('price', isset($drivevehicles->price) ? $drivevehicles->price : '') }}">
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
       
        $("#add_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                name: {
                    required: true
                },

                vehicle_brand_id: {
                    required: true
                },
                vehicle_categorie_id: {
                    required: true
                },
                model:{
                     required: true
                },
                price:{
                     required: true
                }
            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Name'])",
                },
                vehicle_brand_id: {
                    required: "@lang('validation.required',['attribute'=>'Vehicle Brand'])",
                },
                vehicle_categorie_id: {
                    required: "@lang('validation.required',['attribute'=>'Vehicle Category'])",
                },
                model: {
                    required: "@lang('validation.required',['attribute'=>'Model'])",
                },
                price: {
                    required: "@lang('validation.required',['attribute'=>'Price'])",
                }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
        $('#vehicle_brand_id').on('change', function(e) {
            e.preventDefault();
            

            var selectedType= $(this).children("option:selected").val();
            var selectedattrValue= $(this).children("option:selected").attr('data-value-temp');
            
            var str = "1"; 
            var check1 = str.includes(selectedattrValue);


            if(selectedType == "" || selectedattrValue == "" || check1 == false){
                $('.car_window_selection').hide();
            }else{
                $('.car_window_selection').show();
            }
            
        });
    });
</script>
@endsection

resources/views/backend/driver_vehicle/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>  {{ trans('global.update') }} {{ trans('cruds.drivevehicles.title_singular') }}</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('drivevehicles.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                 @include("partials.alert")
                <form action="{{ route('drivevehicles.store') }}" method="POST" enctype="multipart/form-data" id="add_form">
                    @csrf
                    <input type="hidden" name="id" value="{{encrypt($drivevehicles->id)}}">
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.drivevehicles.fields.name') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', isset($drivevehicles->name) ? $drivevehicles->name : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="model">{{ trans('cruds.drivevehicles.fields.modal') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="model" name="model" value="{{ old('model', isset($drivevehicles->model) ? $drivevehicles->model : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="category">{{ trans('cruds.drivevehicles.fields.vehicle_category') }}<span class="required_class">*</span></label>
                        <select class="form-control" name="vehicle_categorie_id" >
                            <option value="">{{ trans('cruds.drivevehicles.fields.select_vehicle_category') }}</option>  
                            @foreach($vehicle_category as $value)
                                @if($value->id == $drivevehicles->vehicle_categorie_id)
                                    <option value="{{$value->id}}" selected="">{{$value->name}}</option>  
                                @else
                                    <option value="{{$value->id}}">{{$value->name}}</option>  
                                @endif
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="category">{{ trans('cruds.drivevehicles.fields.vehicle_brand') }}<span class="required_class">*</span></label>
                        <select class="form-control" name="vehicle_brand_id" id="vehicle_brand_id">
                            <option value="">{{ trans('cruds.drivevehicles.fields.select_vehicle_brand') }}</option>  
                            @foreach($vehicle_brands as $value)
                                @if($value->id == $drivevehicles->vehicle_brand_id)
                                    <option value="{{$value->id}}" data-value-temp="{{$value->vehicle_type_ids}}" selected='' >{{$value->name}}</option>  
                                @else
                                    <option value="{{$value->id}}" data-value-temp="{{$value->vehicle_type_ids}}">{{$value->name}}</option>  
                                @endif
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group car_window_selection" style="display: none">
                        <label for="model">{{ trans('cruds.drivevehicles.fields.number_of_window') }}</label><br>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_3" value="3" checked="">
                            <label class="form-check-label" for="bike_3">3</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_5" value="5">
                            <label class="form-check-label" for="bike_5">5</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="number_of_window" id="bike_7" value="7">
                            <label class="form-check-label" for="bike_7">7</label>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="price">{{ trans('cruds.drivevehicles.fields.price') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="price" name="price" value="{{ old('price', isset($drivevehicles->price) ? $drivevehicles->price : '') }}">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>  
    </div>
</div>    
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
       
        $("#add_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                name: {
                    required: true
                },

                vehicle_brand_id: {
                    required: true
                },
                vehicle_categorie_id: {
                    required: true
                },
                model:{
                     required: true
                },
                price:{
                     required: true
                }
            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Name'])",
                },
                vehicle_brand_id: {
                    required: "@lang('validation.required',['attribute'=>'Vehicle Brand'])",
                },
                vehicle_categorie_id: {
                    required: "@lang('validation.required',['attribute'=>'Vehicle Category'])",
                },
                model: {
                    required: "@lang('validation.required',['attribute'=>'Model'])",
                },
                price: {
                    required: "@lang('validation.required',['attribute'=>'Price'])",
                }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
        $('#vehicle_brand_id').on('change', function(e) {
            e.preventDefault();
            

            var selectedType= $(this).children("option:selected").val();
            var selectedattrValue= $(this).children("option:selected").attr('data-value-temp');
            
            var str = "1"; 
            var check1 = str.includes(selectedattrValue);


            if(selectedType == "" || selectedattrValue == "" || check1 == false){
                $('.car_window_selection').hide();
            }else{
                $('.car_window_selection').show();
            }
            
        });
    });
</script>
@endsection

resources/views/backend/driver_vehicle/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h4>{{ trans('cruds.drivevehicles.title_singular') }} {{ trans('global.list') }}</h4>
            </div>

            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('drivevehicles.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus"></i>
                        {{ trans('global.add') }} {{ trans('cruds.drivevehicles.title_singular') }}
                    </a>
                </div>
            </div>
           
            <div class="col-md-12 mt-3">
               <div class="card">
                    <div class="card-body">
                        @include("partials.alert")
                        <div class="table-responsive">
                            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                                <thead>
                                    <tr>
                                        <th>{{ trans('cruds.drivevehicles.fields.id') }}</th>
                                        <th>{{ trans('cruds.drivevehicles.fields.name') }}</th>
                                        <th>{{ trans('cruds.drivevehicles.fields.modal') }}</th>
                                        <th>{{ trans('cruds.drivevehicles.fields.vehicle_brand') }}</th>
                                         <th>{{ trans('cruds.drivevehicles.fields.vehicle_category') }}</th>
                                        <th>{{ trans('cruds.drivevehicles.fields.price') }}</th>
                                        <th>{{ trans('global.status') }}</th>
                                        <th>{{ trans('global.actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($drive_vehicles as $key => $value)
                                    <tr data-entry-id="{{ $value->id }}">
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $value->name ?? ''}}</td>
                                        <td>{{ $value->model ?? ''}}</td>
                                        <td>{{ ($value->vehicle_brand_name)  ? $value->vehicle_brand_name->name : '-'}}</td>
                                        <td>{{ ($value->vehicle_category_name)  ? $value->vehicle_category_name->name : '-'}}</td>
                                        <td>{{ $value->price ?? ''}}</td>
                                        <td>
                                            @include('partials.switch', ['id'=>
                                            $value->id,'is_active'=>$value->is_active])
                                        </td>
                                        <td>@include('partials.actions', ['id' => $value->id])</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
@endsection

resources/views/backend/driver_vehicle/view.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
               Show Category
               <div class="float-right">
                    <a href="{{ route('category.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <div class="card-body">
                <div class="mb-2">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <!-- Tab panes -->
                            <tr>
                                <th>
                                   Title:
                                </th>
                                <td>
                                    {{ $category->title ?? '-'}}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                   Short Description:
                                </th>
                                <td>
                                    {!! $category->short_description ?? '-' !!}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                   Description:
                                </th>
                                <td>
                                    {!! $category->description ?? '-' !!}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                   Image:
                                </th>
                                <td>
                                    @if($category->image)
                                        <a href="{{ asset(Storage::url($category->image)) }}" target="_blank">
                                            <img src="{{ asset(Storage::url($category->image)) }}" alt="" height=50 width=50>
                                        </a>
                                    @else
                                        '-'
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>
                                   Parent Category:
                                </th>
                                <td>
                                    {{ ($category->category_name) ? $category->category_name->title: '-'}}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>  
@endsection