routes/admin.php
<?php


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['web']], function () {


	Route::get('clear', function (){
    	\Artisan::call('config:cache');
        \Artisan::call('cache:clear');
        \Artisan::call('route:clear');
        \Artisan::call('view:clear');
        \Artisan::call('storage:link');
        echo "ok";
	});

	// Route::get('/link', function () {        
 //   		$target = '/kunden/351322_8001/web/2709369/A2709369/autokosmetik.li/storage/app/public';
 //   		//echo public_path();
 //   		$shortcut = '/kunden/351322_8001/web/2709369/A2709369/autokosmetik.li/public/storage';
 //   		symlink($target, $shortcut);
	// });

	
	Route::get('/register',function () {return redirect('admin/login'); });
	/* Authentication Routes... */
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	Route::post('login', 'Auth\LoginController@login');
	Route::post('logout', 'Auth\LoginController@logout')->name('logout');
	  
	/* Registration Routes... */
	//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
	//Route::post('register', 'Auth\RegisterController@register');
	  
	/* Password Reset Routes... */
	// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
	// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
	// Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
	  
	/* Email Verification Routes... */
	// Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
	// Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
	// Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

	Route::get('/', function () {
	     return redirect('admin/vehicletypes');
	});
	Route::group(['middleware' => 'auth'], function () {
		/*Vehicle Type Route*/
		Route::resource('/vehicletypes', 'VehicleTypeController');  
		Route::resource('/servicecategories', 'ServiceCategoryController');
		Route::resource('/servicesubcategories', 'ServiceSubCategoryController');
        Route::resource('/vehiclecategories', 'VehicleCategoryController');  
		Route::resource('/vehicleconditions', 'VehicleConditionsController');  
		Route::resource('/vehiclebrands', 'VehicleBrandsController');  
		Route::resource('/drivevehicles', 'DriveVehicleController');
		Route::resource('/vehicleservices', 'VehicleServicesController');  
		Route::resource('/servicemangement', 'ServiceManagementController');
        Route::resource('/portfolio', 'PortfolioController');
        Route::resource('/news', 'NewsController');
        Route::resource('/addonservice', 'AddonserviceController');
        Route::resource('/feedback', 'FeedbackController');
	});    
});

routes/web.php
<?php



/*

|--------------------------------------------------------------------------

| Web Routes

|--------------------------------------------------------------------------

|

| Here is where you can register web routes for your application. These

| routes are loaded by the RouteServiceProvider within a group which

| contains the "web" middleware group. Now create something great!

|

*/

Route::get('/', 'WebsiteController@comingsoon')->name('comingsoon');


Route::get('/foo', function () {
    Artisan::call('storage:link');
});




Route::group(['prefix' => 'second_skin'], function() {

	Route::get('/',  'WebsiteController@second_skin')->name('index');

});

Route::group(['prefix' => ''], function() {

	Route::get('/', 'WebsiteController@index')->name('index');

	Route::get('/home', 'WebsiteController@index')->name('index');

	Route::get('/autoaufbereitung', 'WebsiteController@aboutUs')->name('about.us');

	Route::get('/news', 'WebsiteController@news')->name('news');

	Route::get('/news/{id}', 'WebsiteController@newsDetails')->name('newsDetails');

	Route::get('/dienstleistungen', 'WebsiteController@services')->name('services');

	Route::get('/car-cosmetics', 'WebsiteController@carCosmetics')->name('car.cosmetics');

	Route::get('/foil-technology', 'WebsiteController@foilTechnology')->name('foil.technology');

	Route::get('/rim-tire', 'WebsiteController@rimTire')->name('rim.tire');

	Route::get('/voucher', 'WebsiteController@voucher')->name('voucher');

	Route::get('/kontakt', 'WebsiteController@contact')->name('contact');

	Route::get('/projekte', 'WebsiteController@portfolio')->name('portfolio');

	Route::get('/keramikbeschichtung-servfaces', 'WebsiteController@ceramic_coating')->name('ceramic_coating');

	Route::get('/Termin-buchen', 'WebsiteController@bookappointment')->name('bookappointment');

	Route::get('/teflonversiegelung', 'WebsiteController@sealing')->name('sealing');

	Route::get('/swissvax', 'WebsiteController@swissvax')->name('swissvax');

	Route::get('/herkömmlich', 'WebsiteController@conventinal')->name('conventinal');

	Route::get('/spezialfälle', 'WebsiteController@specialcase')->name('specialcase');

	Route::get('/foiltech', 'WebsiteController@foiltech')->name('foiltech');

	Route::get('/lack', 'WebsiteController@paint')->name('paint');

	Route::get('/mono', 'WebsiteController@mono')->name('mono');
	
	Route::get('/autopflege-swissvax', 'WebsiteController@carcare_swissvax')->name('carcare_swissvax');
	Route::get('/auto-innenreinigung', 'WebsiteController@car_interior_cleaning')->name('car_interior_cleaning');
	Route::get('/auto-innenaufbereitung-spezial', 'WebsiteController@car_interior_processing_special')->name('car_interior_processing_special');
	Route::get('/steinschlagschutzfolie', 'WebsiteController@stone_impact_protection_film')->name('stone_impact_protection_film');
	Route::get('/autoscheibentoenung', 'WebsiteController@car_window_tinting')->name('car_window_tinting');
	Route::get('/lederpflege-lederrestauration', 'WebsiteController@leather_care_restoration')->name('leather_care_restoration');
	Route::get('/autofolierung-car-wrapping', 'WebsiteController@car_wrapping')->name('car_wrapping');
	Route::get('/fahrzeugbeschriftung', 'WebsiteController@vehicle_lettering')->name('vehicle_lettering');
	Route::get('/wassertransferdruck', 'WebsiteController@water_transfer_printing')->name('water_transfer_printing');
	Route::get('/verchromungen', 'WebsiteController@chrome_plating')->name('chrome_plating');
	Route::get('/interieur-design', 'WebsiteController@interior_design')->name('interior_design');

	
	

	
	


	Route::get('/email',  function () {

	   $logo = public_path().'/assets/frontend/images/logo.png';

	    return view('frontend.email_template',['name'=>'Wolfinger Fabio','insert_id'=>'9','today' =>'11. April 2021','email'=>'shravangoswami@gmail.com','number'=>'1234567890','logo' => $logo]);

	});

	Route::get('/inquiry',  function () {

	    return view('frontend.inquiry');

	})->name('inquiry');



	Route::post('/step0', 'WebsiteController@ajaxStep0')->name('ajax.step0');

	Route::post('/step1', 'WebsiteController@ajaxStep1')->name('ajax.step1');

	Route::post('/step2', 'WebsiteController@ajaxStep2')->name('ajax.step2');

	Route::post('/step20', 'WebsiteController@ajaxStep20')->name('ajax.step20');

	Route::post('/step3', 'WebsiteController@ajaxStep3')->name('ajax.step3');

	Route::post('/step4', 'WebsiteController@ajaxStep4')->name('ajax.step4');

	Route::post('/step5', 'WebsiteController@ajaxStep5')->name('ajax.step5');

	Route::post('/step6', 'WebsiteController@ajaxStep6')->name('ajax.step6');

	Route::post('/step7', 'WebsiteController@ajaxStep7')->name('ajax.step7');

	Route::post('/step8', 'WebsiteController@ajaxStep8')->name('ajax.step8');





	Route::post('/contactform1', 'WebsiteController@contactform1')->name('ajax.contactform1');

});

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Crypt;
use App\Http\Model\VehicleService;
use App\Http\Model\VehicleConditions;
use Illuminate\Support\Facades\Storage;
use File;

use App\Http\Model\News;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::latest()->get();
        return view('backend.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            if($request->ajax()) {
                $id = Crypt::decrypt($request->id);
                $news = News::where('id',$id)->first();
                if (empty($news->is_active)) {
                    $news->is_active = 1;
                } else {
                    $news->is_active = 0;
                }
                    $news->save();
                return response()->json(['success' => 1]);
            }else{
                if(!empty($request->id)){
                    $this->validate($request, [
                        'name' => 'required',
                        'date' => 'required',
                        'description' => 'required'
                    ]);
                
                    $id = Crypt::decrypt($request->id);
                    $news = News::where('id',$id)->first();
                    
                    $path = '';
                    if ($request->hasFile('image')) {                        
                        $image = $request->file('image');
                        //echo "<pre>"; print_r($image); exit();
                        $filename  = time() . '.' . $image->getClientOriginalExtension();
                        Storage::disk('public')->put('news/'.$filename,  File::get($image));
                        $path = 'news/'.$filename; 
                        $news->image = $path;
                    }
                    

                    $news->name = $request->name;
                    $news->description = $request->description;
                    $news->date = date('Y-m-d', strtotime($request->date));
                    
                    $news->save();
   
                    $message = trans('message.update', ['entity' => trans('cruds.news.title_singular')]);
                }else{
                    $this->validate($request, [
                        'name' => 'required',
                        'date' => 'required',
                        'image' => 'required',
                        'description' => 'required'
                    ]);
                    
                    $path = '';
                    if ($request->hasFile('image')) {                        
                        $image = $request->file('image');
                        //echo "<pre>"; print_r($image); exit();
                        $filename  = time() . '.' . $image->getClientOriginalExtension();
                        Storage::disk('public')->put('news/'.$filename,  File::get($image));
                        $path = 'news/'.$filename; 
                    }
                    
                    $news = new News;
                    $news->name = $request->name;
                    $news->description = $request->description;
                    $news->date = date('Y-m-d', strtotime($request->date));
                    $news->image = $path;
                    $news->save();
                    $message = trans('message.create', ['entity' => trans('cruds.news.title_singular')]);
                }
                   return redirect()->route('news.index')->with('success',$message);
            }
        }catch(\Exception $e){
            if($request->ajax()) {
                 return response()->json(['error' => 1,'message' =>$e->getMessage()]);
            }
            return redirect()->back()->with('danger', $e->getMessage());    
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ServiceManagement  $serviceManagement
     * @return \Illuminate\Http\Response
     */
    public function show(ServiceManagement $servicemanagement)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ServiceManagement  $serviceManagement
     * @return \Illuminate\Http\Response
     */
     public function edit($id)
    {
        $id = Crypt::decrypt($id);
        $news = News::where('id',$id)->first();
        return view('backend.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ServiceManagement  $serviceManagement
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ServiceManagement $serviceManagement)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ServiceManagement  $serviceManagement
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try{
            if($request->ajax()) {
                $id = Crypt::decrypt($request->id);
                News::where('id',$id)->delete();
                return response()->json(['success' => 1]);
            }
        }catch(\Exception $e){
            if($request->ajax()) {
                 return response()->json(['error' => 1,'message' =>$e->getMessage()]);
            }
        } 
    }
}

resources/views/backend/news/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>  {{ trans('global.create') }} {{ trans('cruds.news.title_singular') }}</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('news.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                 @include("partials.alert")
                <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data" id="add_form">
                    @csrf
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.name') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', isset($news->name) ? $news->name : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">{{ trans('cruds.news.fields.description') }}</label>
                        <textarea name="description" class="form-control" id="description" rows="5">
                            {!! old('description', isset($news->description) ? $news->description : '') !!}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.date') }}<span class="required_class">*</span></label>
                        <input type="date" class="form-control" id="date" name="date" value="{{ old('date', isset($news->date) ? $news->date : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.image') }}<span class="required_class">*</span></label>
                        <input type="file" class="form-control" id="image" name="image" value="{{ old('image', isset($news->image) ? $news->image : '') }}">
                    </div>
                    <button type="submit" class="btn btn-primary">{{ trans('global.submit') }}</button>
                </form>
            </div>
        </div>  
    </div>
</div>  
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('description');
        //CKEDITOR.replace('short_description');
       $('#select_type').on('change', function(e) {
            e.preventDefault();
            var selectedType= $(this).children("option:selected").val();
            var selectedattrValue= $(this).children("option:selected").attr('value');
            if(selectedType == "" || selectedattrValue == "" || selectedattrValue == "pricechart"){
                $('.price_text_box').hide();
            }else{
                $('.price_text_box').show();
            }
            
        });
        $("#add_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                name: {
                    required: true
                },
                // description: {
                //     required: function(textarea) {
                //         CKEDITOR.instances[textarea.id].updateElement();
                //         var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                //         return editorcontent.length === 0;
                //     }
                // },
                service_category_id: {
                    required: true
                },
                type: {
                    required: true
                }

            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Name'])",
                },
                description: {
                    required: "@lang('validation.required',['attribute'=>'Description'])",
                },
                service_category_id: {
                    required: "@lang('validation.required',['attribute'=>'Category'])",
                },
                type: {
                    required: "@lang('validation.required',['attribute'=>'Type'])",
                }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
@endsection

resources/views/backend/news/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>  {{ trans('global.update') }} {{ trans('cruds.news.title_singular') }}</h2>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('news.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
            <br>
            <div class="col-md-12">
                 @include("partials.alert")
                <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data" id="add_form">
                    @csrf
                     <input type="hidden" name="id" value="{{encrypt($news->id)}}">
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.name') }}<span class="required_class">*</span></label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ old('name', isset($news->name) ? $news->name : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">{{ trans('cruds.news.fields.description') }}</label>
                        <textarea name="description" class="form-control" id="description" rows="5">
                            {!! old('description', isset($news->description) ? $news->description : '') !!}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.date') }}<span class="required_class">*</span></label>
                        <input type="date" class="form-control" id="date" name="date" value="{{ old('date', isset($news->date) ? $news->date : '') }}">
                    </div>
                    <div class="form-group">
                        <label for="title">{{ trans('cruds.news.fields.image') }}<span class="required_class">*</span></label>
                        <input type="file" class="form-control" id="image" name="image" value="{{ old('image', isset($news->image) ? $news->image : '') }}">
                    </div>
                    <div class="mb-3">
                        <img src="{{asset(Storage::url($news->image)) ?? ''}}" alt="" height=100 width=100>
                    </div>
                    <button type="submit" class="btn btn-primary">{{ trans('global.submit') }}</button>
                </form>
            </div>
        </div>  
    </div>
</div>  
@endsection
@section('scripts')
<script type="text/javascript">
    $(function() {
        CKEDITOR.replace('description');
        //CKEDITOR.replace('short_description');
        $("#add_form").validate({
            // Specify validation rules       
            ignore: [],
            rules: {
                name: {
                    required: true
                },
                // description: {
                //     required: function(textarea) {
                //         CKEDITOR.instances[textarea.id].updateElement();
                //         var editorcontent = textarea.value.replace(/<[^>]*>/gi, '');
                //         return editorcontent.length === 0;
                //     }
                // },
                // service_category_id: {
                //     required: true
                // },
                // type: {
                //     required: true
                // }

            },
            // Specify validation error messages
            messages: {
                name: {
                    required: "@lang('validation.required',['attribute'=>'Name'])",
                },
                // description: {
                //     required: "@lang('validation.required',['attribute'=>'Description'])",
                // },
                // service_category_id: {
                //     required: "@lang('validation.required',['attribute'=>'Category'])",
                // },
                // type: {
                //     required: "@lang('validation.required',['attribute'=>'Type'])",
                // }
            },

            // Make sure the form is submitted to the destination defined
            // in the "action" attribute of the form when valid
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
@endsection

resources/views/backend/news/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h4>{{ trans('cruds.news.title_singular') }} {{ trans('global.list') }}</h4>
            </div>

            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('news.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus"></i>
                        {{ trans('global.add') }} {{ trans('cruds.news.title_singular') }}
                    </a>
                </div>
            </div>
            <div class="col-md-12  mt-3">
                <div class="card">
                    <div class="card-body">
                        @include("partials.alert")
                        <div class="table-responsive">
                            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                                <thead>
                                    <tr>
                                        <th>{{ trans('cruds.news.fields.id') }}</th>
                                        <th>{{ trans('cruds.news.fields.name') }}</th>
                                        <!-- <th>{{ trans('cruds.news.fields.description') }}</th> -->
                                        <th>{{ trans('global.status') }}</th>
                                        <th>{{ trans('global.actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($news as $key => $value)
                                    <tr data-entry-id="{{ $value->id }}">
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $value->name ?? ''}}</td>
                                        <!-- <td>{!! $value->description ?? '-' !!}</td> -->
                                        <td>
                                            @include('partials.switch', ['id'=>
                                            $value->id,'is_active'=>$value->is_active])
                                        </td>
                                        <td>@include('partials.actions', ['id' => $value->id])</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>    
@endsection

resources/views/backend/news/view.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <br>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Blog Details</h2>
        </div>
        <div class="col-md-6">
            <div class="float-right">
                <a href="{{ route('blogs.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <br>
        <div class="col-md-12">
            <br><br>
            <div class="todo-title">
                <strong>Title: </strong> {{ $blog->title ?? ''}}
            </div>
            <br>
            <div class="todo-description">
                <strong>Description: </strong> {{ $blog->description ?? ''}}
            </div>
            <br>
        </div>
    </div>
</div>
@endsection